---
- name: Setup PostgreSQL & Redis
  hosts: app
  become: yes

  vars:
    postgres_version: "16"
    postgres_db_name: "form_sender"
    postgres_user: "form_user"
    postgres_password: "formuseradmin"

    postgres_conf_dir: "/etc/postgresql/16/main"

    redis_bind: "127.0.0.1"
    redis_port: 6379

  tasks:
    - name: Install packages for postgresql and redis
      tags: install
      apt:
        name:
          - postgresql
          - postgresql-contrib
          - python3-psycopg2
          - redis-server
        state: present
        update_cache: yes

    - name: Ensure PostgreSQL is running and enabled
      systemd:
        name: postgresql
        state: started
        enabled: yes

    - name: Configure postgresql.conf (listen on localhost only)
      tags: install
      lineinfile:
        path: "{{ postgres_conf_dir }}/postgresql.conf"
        regexp: '^#?listen_addresses\s*='
        line: "listen_addresses = '127.0.0.1'"
        state: present
      notify: Restart PostgreSQL

    - name: Change postgres local auth to trust
      become: yes
      lineinfile:
        path: /etc/postgresql/16/main/pg_hba.conf
        regexp: '^local\s+all\s+postgres\s+peer'
        line: 'local   all             postgres                                trust'
        state: present
      notify: Restart PostgreSQL   # ← これも restart させておくと安心

    - name: Change local all all peer to md5
      become: yes
      lineinfile:
        path: "/etc/postgresql/{{ postgres_version }}/main/pg_hba.conf"
        regexp: '^local\s+all\s+all\s+peer$'
        line: 'local   all             all                                     md5'
        backup: yes
      notify: Restart PostgreSQL

    - name: Restart PostgreSQL now if config changed
      meta: flush_handlers


    - name: Create application database user
      tags: install
      community.postgresql.postgresql_user:
        name: "{{ postgres_user }}"
        password: "{{ postgres_password }}"
        role_attr_flags: "LOGIN"
        state: present

    - name: Create application database
      tags: install
      community.postgresql.postgresql_db:
        name: "{{ postgres_db_name }}"
        owner: "{{ postgres_user }}"
        encoding: "UTF8"
        state: present

    - name: Apply SQL file
      community.postgresql.postgresql_query:
        db: "{{ postgres_db_name }}"
        login_user: "{{ postgres_user }}"
        login_password: "{{ postgres_password }}"
        query: "{{ lookup('file', 'files/setup.sql') }}"

    # ---------- Redis ----------
    - name: Configure redis to bind on localhost
      tags: install
      lineinfile:
        path: /etc/redis/redis.conf
        regexp: '^bind\s+'
        line: "bind {{ redis_bind }}"
        state: present
      notify: Restart Redis

    - name: Configure redis supervised by systemd
      tags: install
      lineinfile:
        path: /etc/redis/redis.conf
        regexp: '^supervised\s+'
        line: "supervised systemd"
        state: present
      notify: Restart Redis

    - name: Ensure Redis is running and enabled
      tags: restart
      systemd:
        name: redis-server
        state: started
        enabled: yes

  handlers:
    - name: Restart PostgreSQL
      tags: restart
      systemd:
        name: postgresql
        state: restarted

    - name: Restart Redis
      tags: restart
      systemd:
        name: redis-server
        state: restarted
