---
- name: Deploy app to EC2
  hosts: app
  become: yes

  vars:
    app_dir: /var/www/app
    repo_url: "https://github.com/thecatblake/form-auto-sender.git"
    branch: "main"
    rust_server_name: contact_discovery

  tasks:
    - name: install packages
      apt:
        name:
          - git
          - nodejs
          - npm
          - build-essential
          - pkg-config
          - libssl-dev
          - curl
        state: present
        update_cache: yes

    - name: Download rustup installer
      get_url:
        url: https://sh.rustup.rs
        dest: "/home/deploy/rustup-init.sh"
        mode: "0755"

    - name: Install rust
      shell: |
        /home/deploy/rustup-init.sh -y --no-modify-path
      args:
        creates: "/home/deploy/.cargo/bin/rustc"

    - name: mkdir app
      file:
        path: "{{ app_dir }}"
        state: directory
        owner: deploy
        group: deploy
        mode: "0755"
    
    - name: clone repo
      become: yes
      become_user: deploy
      git:
        repo: "{{ repo_url }}"
        dest: "{{ app_dir }}"
        version: "{{ branch }}"
        force: yes

    - name: build rust server
      shell: |
        source /home/deploy/.bashrc
        cd {{ app_dir }}/{{ rust_server_name }}
        cargo build --release
      args:
        chdir: "{{ app_dir }}"

    - name: copy rust server to /usr/local/bin
      copy:
        src: "{{ app_dir }}/{{ rust_server_name }}/target/release/{{ rust_server_name }}"
        dest: "/usr/local/bin/{{ rust_server_name }}"
        mode: "0755"
    
    - name: create systemd service for rust
      copy:
        dest: /etc/systemd/system/{{ rust_server_name }}.service
        content: |
          [Unit]
          Description=Rust App {{ rust_server_name }}
          After=network.target

          [Service]
          ExecStart=/usr/local/bin/{{ rust_server_name }}
          Restart=always
          User=deploy

          [Install]
          WantedBy=multi-user.target
    
    - name: Enable and start systemd
      systemd:
        name: "{{ rust_server_name }}"
        state: restarted
        enabled: yes

    - name: npm install
      become: yes
      become_user: deploy
      npm:
        path: "{{ app_dir }}/contact_submitter"
        production: yes