---
- name: Deploy app to EC2
  hosts: app
  become: yes

  vars:
    app_dir: /var/www/app
    repo_url: "https://github.com/thecatblake/form-auto-sender.git"
    branch: "main"
    rust_server_name: contact_discovery

  tasks:
    - name: install packages
      tags: install
      apt:
        name:
          - git
          - nodejs
          - npm
          - build-essential
          - pkg-config
          - libssl-dev
          - curl
        state: present
        update_cache: yes
        cache_valid_time: 3600


    - name: Download rustup installer
      tags: install
      become_user: deploy
      get_url:
        url: https://sh.rustup.rs
        dest: "/home/deploy/rustup-init.sh"
        mode: "0755"

    - name: Install rust
      tags: install
      become_user: deploy
      shell: |
        /home/deploy/rustup-init.sh -y --no-modify-path
      args:
        creates: "/home/deploy/.cargo/bin/rustc"

    - name: mkdir app
      tags: install
      file:
        path: "{{ app_dir }}"
        state: directory
        owner: deploy
        group: deploy
        mode: "0755"
    
    - name: clone repo
      tags: build
      become: yes
      become_user: deploy
      git:
        repo: "{{ repo_url }}"
        dest: "{{ app_dir }}"
        version: "{{ branch }}"
        force: yes

    - name: build rust server
      tags: build
      become_user: deploy
      shell: |
        export PATH="$HOME/.cargo/bin:$PATH"
        cd {{ app_dir }}/{{ rust_server_name }}
        cargo build --release
      args:
        chdir: "{{ app_dir }}"

    - name: copy rust server to /usr/local/bin
      tags: build
      become: yes
      copy:
        remote_src: true
        src: "{{ app_dir }}/{{ rust_server_name }}/target/release/{{ rust_server_name }}"
        dest: "/usr/local/bin/{{ rust_server_name }}"
        mode: "0755"
        owner: root
        group: root
    
    - name: create systemd service for rust
      tags: build
      copy:
        dest: /etc/systemd/system/{{ rust_server_name }}.service
        content: |
          [Unit]
          Description=Rust App {{ rust_server_name }}
          After=network.target

          [Service]
          ExecStart=/usr/local/bin/{{ rust_server_name }}
          Restart=always
          User=deploy

          [Install]
          WantedBy=multi-user.target
    
    - name: Enable and start systemd
      tags: restart
      systemd:
        name: "{{ rust_server_name }}"
        state: restarted
        enabled: yes

    - name: npm install for submitter
      tags: build
      become: yes
      become_user: deploy
      npm:
        path: "{{ app_dir }}/contact_submitter"
        production: no

    - name: npm install for gateway
      tags: build
      become: yes
      become_user: deploy
      npm:
        path: "{{ app_dir }}/gateway"
        production: no

    - name: Build gateway
      tags: build
      command: npm run build
      args:
        chdir: "{{ app_dir }}/gateway"

    - name: Install systemd unit for gateway
      tags: build
      template:
        src: "gateway.service.j2"
        dest: "/etc/systemd/system/gateway.service"
        owner: root
        group: root
        mode: "0644"
      notify:
        - daemon-reload
        - restart gateway

  handlers:
    - name: daemon-reload
      tags: restart
      systemd:
        daemon_reload: yes

    - name: restart gateway
      tags: restart
      systemd:
        name: "gateway"
        state: restarted
        enabled: yes
