---
- name: Deploy app to EC2
  hosts: app
  become: yes

  vars:
    app_dir: /var/www/app
    repo_url: "https://github.com/thecatblake/form-auto-sender.git"
    branch: "main"

  tasks:
    - name: install packages
      apt:
        name:
          - git
          - nodejs
          - npm
        state: present
        update_cache: yes

    - name: mkdir app
      file:
        path: "{{ app_dir }}"
        state: directory
        owner: deploy
        group: deploy
        mode: "0755"
    
    - name: clone repo
      become: yes
      become_user: deploy
      git:
        repo: "{{ repo_url }}"
        dest: "{{ app_dir }}"
        version: "{{ branch }}"
        force: yes

    - name: npm install
      become: yes
      become_user: deploy
      npm:
        path: "{{ app_dir }}/contact_submitter"
        production: yes