---
- name: Setup Prometheus & Grafana on single server
  hosts: monitoring
  become: yes
  vars:
    prometheus_version: "2.55.0"
    prometheus_user: "prometheus"
    prometheus_group: "prometheus"
    prometheus_install_dir: "/opt/prometheus"
    prometheus_data_dir: "/var/lib/prometheus"
    prometheus_config_dir: "/etc/prometheus"

  tasks:
    - name: install basic packages
      apt:
        name:
          - curl
          - wget
          - tar
          - adduser
          - software-properties-common
        update_cache: yes
        state: present

    - name: Create Prometheus user and group
      user:
        name: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"
        system: yes
        shell: /usr/sbin/nologin
        create_home: no

    - name: create directories for prometheus
      file:
        path: "{{ item  }}"
        state: directory
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"
        mode: "0755"
      loop:
        - "{{ prometheus_install_dir }}"
        - "{{ prometheus_data_dir }}"
        - "{{ prometheus_config_dir }}"

    - name: Download Prometheus tarball
      get_url:
        url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
        dest: "/tmp/prometheus-{{ prometheus_version }}.tar.gz"
        mode: "0644"

    - name: Extract Prometheus
      unarchive:
        src: "/tmp/prometheus-{{ prometheus_version }}.tar.gz"
        dest: "/tmp"
        remote_src: yes

    
    - name: Install Prometheus binaries
      copy:
        src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
        dest: "/usr/local/bin/{{ item }}"
        owner: root
        group: root
        mode: "0755"
        remote_src: yes
      loop:
        - prometheus
        - promtool

    - name: Copy console libraries
      copy:
        src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
        dest: "{{ prometheus_install_dir }}/{{ item }}"
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"
        mode: "0755"
        remote_src: yes
      loop:
        - consoles
        - console_libraries

    - name: Deploy Prometheus config
      template:
        src: "templates/prometheus.yml.j2"
        dest: "{{ prometheus_config_dir }}/prometheus.yml"
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"
        mode: "0644"
      notify: Restart Prometheus

    - name: Install systemd unit for Prometheus
      copy:
        src: "files/prometheus.service"
        dest: "/etc/systemd/system/prometheus.service"
        owner: root
        group: root
        mode: "0644"
      notify:
        - Daemon reload
        - Restart Prometheus