---
- name: Setup Prometheus & Grafana on single server
  hosts: monitoring
  become: yes
  vars:
    prometheus_version: "2.55.0"
    prometheus_user: "prometheus"
    prometheus_group: "prometheus"
    prometheus_install_dir: "/opt/prometheus"
    prometheus_data_dir: "/var/lib/prometheus"
    prometheus_config_dir: "/etc/prometheus"
    node_exporter_version: "1.7.0"
    node_exporter_install_dir: "/opt/node_exporter"

  tasks:
    - name: install basic packages
      apt:
        name:
          - curl
          - wget
          - tar
          - adduser
          - software-properties-common
        update_cache: yes
        state: present

    - name: Create Prometheus group
      group:
        name: "{{ prometheus_group }}"
        system: yes


    - name: Create Prometheus user and group
      user:
        name: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"
        system: yes
        shell: /usr/sbin/nologin
        create_home: no

    - name: create directories for prometheus
      file:
        path: "{{ item  }}"
        state: directory
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"
        mode: "0755"
      loop:
        - "{{ prometheus_install_dir }}"
        - "{{ prometheus_data_dir }}"
        - "{{ prometheus_config_dir }}"

    - name: Download Prometheus tarball
      get_url:
        url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
        dest: "/tmp/prometheus-{{ prometheus_version }}.tar.gz"
        mode: "0644"

    - name: Extract Prometheus
      unarchive:
        src: "/tmp/prometheus-{{ prometheus_version }}.tar.gz"
        dest: "/tmp"
        remote_src: yes

    
    - name: Install Prometheus binaries
      copy:
        src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
        dest: "/usr/local/bin/{{ item }}"
        owner: root
        group: root
        mode: "0755"
        remote_src: yes
      loop:
        - prometheus
        - promtool

    - name: Copy console libraries
      copy:
        src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
        dest: "{{ prometheus_install_dir }}/{{ item }}"
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"
        mode: "0755"
        remote_src: yes
      loop:
        - consoles
        - console_libraries

    - name: Deploy Prometheus config
      template:
        src: "templates/prometheus.yml.j2"
        dest: "{{ prometheus_config_dir }}/prometheus.yml"
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"
        mode: "0644"
      notify: Restart Prometheus

    - name: Install systemd unit for Prometheus
      copy:
        src: "files/prometheus.service"
        dest: "/etc/systemd/system/prometheus.service"
        owner: root
        group: root
        mode: "0644"
      notify:
        - Daemon reload
        - Restart Prometheus

    - name: Create install directory for node_exporter
      file:
        path: "{{ node_exporter_install_dir }}"
        state: directory
        owner: "{{ node_exporter_user }}"
        group: "{{ node_exporter_group }}"
        mode: "0755"

    - name: Download node_exporter
      get_url:
        url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
        dest: "/tmp/node_exporter-{{ node_exporter_version }}.tar.gz"
        mode: "0644"
    
    - name: Extract node_exporter
      unarchive:
        src: "/tmp/node_exporter-{{ node_exporter_version }}.tar.gz"
        dest: "/tmp"
        remote_src: yes

    - name: Install node_exporter binary
      copy:
        src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
        dest: "/usr/local/bin/node_exporter"
        owner: root
        group: root
        mode: "0755"
        remote_src: yes

    - name: Install systemd unit for node_exporter
      copy:
        src: "files/node_exporter.service"
        dest: "/etc/systemd/system/node_exporter.service"
        owner: root
        group: root
        mode: "0644"
      notify:
        - Daemon reload
        - Restart node_exporter


  handlers:
    - name: Daemon reload
      systemd:
        daemon_reload: yes

    - name: Restart Prometheus
      systemd:
        name: prometheus
        enabled: yes
        state: restarted
  
    - name: Restart node_exporter 
      systemd:
        name: node_exporter
        enabled: yes
        state: restarted